/**
 * The single seam onto the underlying icon library. Nothing outside this
 * file (and AppIcon.vue, which consumes it) may import from
 * 'lucide-vue-next' — swapping icon providers later means editing only
 * this map.
 */
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Eye,
  EyeOff,
  ExternalLink,
  Globe,
  Home,
  Inbox,
  Info,
  Loader2,
  LogOut,
  Menu,
  Minus,
  Monitor,
  MoreHorizontal,
  Moon,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Sun,
  Trash2,
  Upload,
  Download,
  User,
  X,
  type LucideIcon,
} from 'lucide-vue-next'

export const iconRegistry = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  eye: Eye,
  'eye-off': EyeOff,
  'external-link': ExternalLink,
  globe: Globe,
  home: Home,
  inbox: Inbox,
  info: Info,
  loader: Loader2,
  'log-out': LogOut,
  menu: Menu,
  minus: Minus,
  monitor: Monitor,
  'more-horizontal': MoreHorizontal,
  moon: Moon,
  pencil: Pencil,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  sun: Sun,
  trash: Trash2,
  upload: Upload,
  download: Download,
  user: User,
  close: X,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof iconRegistry
