/**
 * The single seam onto the underlying icon library. Nothing outside this
 * file (and AppIcon.vue, which consumes it) may import from
 * 'lucide-vue-next' — swapping icon providers later means editing only
 * this map.
 */
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Bot,
  ChartLine,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Code,
  Compass,
  Eye,
  EyeOff,
  ExternalLink,
  Gem,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Inbox,
  Info,
  Layers,
  Loader2,
  Lock,
  LogOut,
  Menu,
  Minus,
  Monitor,
  MoreHorizontal,
  Moon,
  Network,
  NotebookPen,
  Palette,
  Pencil,
  Plus,
  RefreshCw,
  Route,
  Search,
  Settings,
  Shield,
  Sparkles,
  Sun,
  Trash2,
  Upload,
  Download,
  User,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-vue-next'

export const iconRegistry = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'book-open': BookOpen,
  bot: Bot,
  'chart-line': ChartLine,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  code: Code,
  compass: Compass,
  eye: Eye,
  'eye-off': EyeOff,
  'external-link': ExternalLink,
  gem: Gem,
  globe: Globe,
  'graduation-cap': GraduationCap,
  heart: Heart,
  home: Home,
  inbox: Inbox,
  info: Info,
  layers: Layers,
  loader: Loader2,
  lock: Lock,
  'log-out': LogOut,
  menu: Menu,
  minus: Minus,
  monitor: Monitor,
  'more-horizontal': MoreHorizontal,
  moon: Moon,
  network: Network,
  'notebook-pen': NotebookPen,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  refresh: RefreshCw,
  route: Route,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  trash: Trash2,
  upload: Upload,
  download: Download,
  user: User,
  close: X,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof iconRegistry
