/**
 * The single seam onto the underlying icon library. Nothing outside this
 * file (and AppIcon.vue, which consumes it) may import from
 * 'lucide-vue-next' — swapping icon providers later means editing only
 * this map.
 */
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Brain,
  Calendar,
  CalendarDays,
  ChartLine,
  Check,
  CheckCircle2,
  Circle,
  CircleDot,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Code,
  Coffee,
  Compass,
  Cpu,
  Eye,
  EyeOff,
  ExternalLink,
  File,
  FileText,
  Flame,
  Gem,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Inbox,
  Info,
  Layers,
  Link2,
  ListTodo,
  Loader2,
  Lock,
  LogOut,
  Menu,
  MessageSquare,
  Minus,
  Monitor,
  MoreHorizontal,
  Moon,
  Network,
  NotebookPen,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pencil,
  Play,
  Plus,
  QrCode,
  RefreshCw,
  Route,
  Search,
  Send,
  Settings,
  Shield,
  Sparkles,
  Star,
  Sun,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  Download,
  User,
  Video,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-vue-next'

export const iconRegistry = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'bar-chart': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  bot: Bot,
  brain: Brain,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'chart-line': ChartLine,
  check: Check,
  'check-circle': CheckCircle2,
  circle: Circle,
  'circle-dot': CircleDot,
  clock: Clock,
  coffee: Coffee,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  eye: Eye,
  'eye-off': EyeOff,
  'external-link': ExternalLink,
  file: File,
  'file-text': FileText,
  flame: Flame,
  gem: Gem,
  globe: Globe,
  'graduation-cap': GraduationCap,
  heart: Heart,
  home: Home,
  inbox: Inbox,
  info: Info,
  layers: Layers,
  link: Link2,
  'list-todo': ListTodo,
  loader: Loader2,
  lock: Lock,
  'log-out': LogOut,
  menu: Menu,
  'message-square': MessageSquare,
  minus: Minus,
  monitor: Monitor,
  'more-horizontal': MoreHorizontal,
  moon: Moon,
  network: Network,
  'notebook-pen': NotebookPen,
  palette: Palette,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  paperclip: Paperclip,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  'qr-code': QrCode,
  refresh: RefreshCw,
  route: Route,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  trash: Trash2,
  'trending-up': TrendingUp,
  upload: Upload,
  download: Download,
  user: User,
  video: Video,
  close: X,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof iconRegistry
