/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./../components/AppAvatar.vue')['default']
    AppBadge: typeof import('./../components/AppBadge.vue')['default']
    AppButton: typeof import('./../components/AppButton.vue')['default']
    AppCard: typeof import('./../components/AppCard.vue')['default']
    AppDialog: typeof import('./../components/AppDialog.vue')['default']
    AppDrawer: typeof import('./../components/AppDrawer.vue')['default']
    AppEmpty: typeof import('./../components/AppEmpty.vue')['default']
    AppIcon: typeof import('./../components/AppIcon.vue')['default']
    AppInput: typeof import('./../components/AppInput.vue')['default']
    AppLoading: typeof import('./../components/AppLoading.vue')['default']
    AppPageHeader: typeof import('./../components/AppPageHeader.vue')['default']
    AppPagination: typeof import('./../components/AppPagination.vue')['default']
    AppSearch: typeof import('./../components/AppSearch.vue')['default']
    AppSection: typeof import('./../components/AppSection.vue')['default']
    AppSkeleton: typeof import('./../components/AppSkeleton.vue')['default']
    AppTag: typeof import('./../components/AppTag.vue')['default']
    AppTooltip: typeof import('./../components/AppTooltip.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GlassScene: typeof import('./../components/experience/GlassScene.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatTile: typeof import('./../components/StatTile.vue')['default']
  }
}
